import java.sql.*;
import javax.swing.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
public class autoge2 extends javax.swing.JFrame {
String p;
     public autoge2(String p) {
         this.p=p;
        initComponents();
    }
    /**
     * Creates new form autoge2
     */
    public autoge2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        oo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ssid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oo.setColumns(20);
        oo.setRows(5);
        jScrollPane1.setViewportView(oo);

        jLabel1.setText("Student ID");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu3.setText("Options");

        jMenuItem1.setText("Show Student personal Information");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Show Student Result");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Guardian Remark");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     try
        {            
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/studentM","admin3","admin3");
            String Query = "select  * from STUDENTREG where STUDENT_PASSWORD  LIKE '%"+p+"%'";
            PreparedStatement statement = con.prepareStatement(Query);
            ResultSet result = statement.executeQuery(); 
            if (result.next())
            {   
                String STUDENT_NAME=result.getString("STUDENT_NAME").toString().trim();
                String STUDENT_FATHER_NAME=result.getString("STUDENT_FATHER_NAME").toString().trim();
                String STUDENT_MOTHER_NAME=result.getString("STUDENT_MOTHER_NAME").toString().trim();
                String SSC_SCHOOLNAME=result.getString("SSC_SCHOOLNAME").toString().trim();
                String HSC_COLLEGENAME=result.getString("HSC_COLLEGENAME").toString().trim();
                String LOCAL_GUARDIAN=result.getString("LOCAL_GUARDIAN").toString().trim();
                String GUARDIAN_PHONENUM=result.getString("GUARDIAN_PHONENUM").toString().trim();
                String PERMANENT_ADDRESS=result.getString("PERMANENT_ADDRESS").toString().trim();
                String PRESENT_ADDRESS=result.getString("PRESENT_ADDRESS").toString().trim();
                String FATHER_OCCUPATION=result.getString("FATHER_OCCUPATION").toString().trim();
                String MOTHER_OCCUPATION=result.getString("MOTHER_OCCUPATION").toString().trim();
                String ADVISOR=result.getString("ADVISOR").toString().trim();
                String STUDENT_PASSWORD=result.getString("STUDENT_PASSWORD").toString().trim();
                String SSC_GPA=result.getString("SSC_GPA").toString().trim();
                String HSC_GPA=result.getString("HSC_GPA").toString().trim();
                String MOTHER_ANNUAL_INCOME=result.getString("MOTHER_ANNUAL_INCOME").toString().trim();
                String FATHER_ANNUAL_INCOME=result.getString("FATHER_ANNUAL_INCOME").toString().trim();
                String DATE_OF_BATH=result.getString("DATE_OF_BATH").toString().trim();
                String STUDENT_ID=result.getString("STUDENT_ID").toString().trim();
                String STUDENT_EMAIL=result.getString("STUDENT_EMAIL").toString().trim();
                
                        //oo.setText("Student id: "+id); 
                        oo.setText("STUDENT_NAME:\n"+STUDENT_NAME+"\n\n   "
                                  +""+"STUDENT_FATHER_NAME :\n"+STUDENT_FATHER_NAME+"\n\n  "
                                  + ""+"STUDENT_MOTHER_NAME :\n"+STUDENT_MOTHER_NAME+"\n\n  "
                                  + ""+"SSC_SCHOOLNAME :\n"+SSC_SCHOOLNAME+"\n\n  "
                                  + ""+"HSC_COLLEGENAME :\n"+HSC_COLLEGENAME+"\n\n  "
                                  + ""+"LOCAL_GUARDIAN :\n"+LOCAL_GUARDIAN+"\n\n  "
                                  + ""+"GUARDIAN_PHONENUM :\n"+GUARDIAN_PHONENUM+"\n\n  "
                                  + ""+"PERMANENT_ADDRESS :\n"+PERMANENT_ADDRESS+"\n\n  "
                                  + ""+"PRESENT_ADDRESS :\n"+PRESENT_ADDRESS+"\n\n  "
                                  + ""+"FATHER_OCCUPATION :\n"+FATHER_OCCUPATION+"\n\n  "
                                  + ""+"MOTHER_OCCUPATION :\n"+MOTHER_OCCUPATION+"\n\n  "
                                  + ""+"ADVISOR :\n"+ADVISOR+"\n\n  "
                                  + ""+"STUDENT_PASSWORD :\n"+STUDENT_PASSWORD+"\n\n  "
                                  + ""+"SSC_GPA :\n"+SSC_GPA+"\n\n  "
                                  + ""+"HSC_GPA :\n"+HSC_GPA+"\n\n  "
                                  + ""+"MOTHER_ANNUAL_INCOME :\n"+MOTHER_ANNUAL_INCOME+"\n\n  "
                                  + ""+"FATHER_ANNUAL_INCOME :\n"+FATHER_ANNUAL_INCOME+"\n\n  "
                                   + ""+"DATE_OF_BATH :\n"+DATE_OF_BATH+"\n\n  "       
                                  + ""+"STUDENT_ID :\n"+STUDENT_ID+"\n\n  "
                                  + ""+"STUDENT_EMAIL :\n"+STUDENT_EMAIL+"\n\n  "
                                  );
                       
                        
                
            }                     
            else
            {                  
               oo.setText("This ID is not registered");              
            }                      
            statement.close();
            con.close();        
        }
        catch(SQLException se){
             se.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();     
            oo.setText("Exception occurred while searching in the STUDENTREG table");
        } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       // close();
       //g5 j=new g5 ();
       //j.setVisible(true);
       try
        {            
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/studentM","admin3","admin3");
            String Query = "select  STUDENT_ID from STUDENTRESULT where STUDENT_ID LIKE '%"+ssid.getText()+"%'";
            PreparedStatement statement = con.prepareStatement(Query);
            ResultSet result = statement.executeQuery(); 
            if (result.next())
            {   
                String dbasePassword=result.getString("STUDENT_ID").toString().trim();
                String enteredPassword=ssid.getText().trim();
                if(dbasePassword.equals(enteredPassword))
                {oo.setText("Welcome");
                guardianshowresult h=new guardianshowresult(dbasePassword);
                
                 
                           close();
                         g5 sel=new g5 (dbasePassword);
                           sel.setVisible(true);
                           
                           
                          
                
                
                }
                
                else
  			oo.setText("Sorry you are unauthorized");        
            }                     
            else
            {                  
               oo.setText("This ID is not registered");              
            }                      
            statement.close();
            con.close();        
        }
        catch(SQLException se){
             se.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();     
            oo.setText("Exception occurred while searching in the STUDENTREG table");
        } 
       
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                            close();
                            g4 i=new g4 ();
                            i.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                          close();
                         autogGuardien sel=new autogGuardien ();
                          sel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
public void close()
{
    this.setVisible(false);
    this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autoge2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autoge2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autoge2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autoge2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autoge2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea oo;
    private javax.swing.JTextField ssid;
    // End of variables declaration//GEN-END:variables
}
